FROM node:12-bullseye-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python2 \
        python3 \
        make \
        g++ \
        git \
        ca-certificates && \
    ln -sf /usr/bin/python2 /usr/local/bin/python && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json yarn.lock ./
COPY local-deps ./local-deps

RUN yarn install --frozen-lockfile --network-timeout 600000 --ignore-engines

RUN mkdir -p tmp

EXPOSE 8080

ENV NODE_ENV=development

CMD ["yarn", "start"]
